global: 
  scrape_interval: 1s
  
scrape_configs: 
- job_name: 'prometheus' 
  scrape_interval: 1s 
  static_configs: 
  - targets: ['localhost:9090'] 
- job_name: 'hyperledger_metrics' 
  scrape_interval: 1s
  static_configs: 
  - targets: ['peer0.org1.example.com:9443', 'orderer.example.com:9446']
